adx_attachfilelabel: ''
adx_attachfilemaxsize: 
adx_attachfilestoragelocation: 756150000
adx_containername: ''
adx_entitypermissionsenabled: true
adx_formname: Information
adx_hideformonsuccess: true
adx_maximumnooffiles: 5
adx_mode: 100000001
adx_movepreviouspermitted: true
adx_name: Job Application-deleted
adx_nextstep: ''
adx_referencequerystringisprimarykey: true
adx_storageaccountname: ''
adx_successmessage: ''
adx_targetentitylogicalname: ss_jobapplications
adx_type: 100000001
adx_validationsummarylinksenabled: true
adx_webform: 6c049b06-3a8e-4ef3-9a25-2374dde89d39
adx_webformstepid: 55da3b1c-dd5d-4554-925f-c93334405259
statecode: 1
statuscode: 2
