adx_attachfilemaxsize: 
adx_attachfilestoragelocation: 756150000
adx_captcharequired: false
adx_entityformid: 3f82e783-941d-469b-8933-a7017ab22640
adx_entityname: ss_jobapplications
adx_entitypermissionsenabled: true
adx_entitysourcetype: 756150001
adx_formname: Information
adx_geolocation_maptype: 756150000
adx_hideformonsuccess: true
adx_lcid: 1033
adx_maximumnooffiles: 5
adx_mode: 100000002
adx_name: View Job Application
adx_onsuccess: 756150000
adx_recordidquerystringparametername: id
adx_redirecturl: 
adx_redirectwebpage: 
adx_showcaptchaforauthenticatedusers: false
adx_tabname: General
