adx_amountColumnName: ''
adx_attachfilelabel: >-
  [
    {
      "LCID": 1033,
      "Value": ""
    }
  ]
adx_attachfilemaxsize: 
adx_attachfilestoragelocation: 756150000
adx_docusignTemplate: ''
adx_entitypermissionsenabled: true
adx_entitysourcetype: 100000001
adx_filecontent: 
adx_formname: Information
adx_geolocation_maptype: 756150000
adx_hideformonsuccess: true
adx_isESignatureEnabled: false
adx_isPaymentEnabled: false
adx_maximumnooffiles: 5
adx_mode: 100000002
adx_movepreviouspermitted: false
adx_name: Job Application
adx_nextstep: ceb47fa1-b1eb-44e7-afe0-832d0ef39784
adx_primarykeyattributelogicalname: ss_jobapplicationsid
adx_primarykeyquerystringparametername: id
adx_referenceentitysourcetype: 100000001
adx_referencequerystringisprimarykey: true
adx_tabname: General
adx_targetentitylogicalname: ss_jobapplications
adx_type: 100000001
adx_validationsummarylinksenabled: true
adx_webform: 007eb888-74a0-4ee2-aa98-f1de2cbcbc5a
adx_webFormMetadatas: []
adx_webformstepid: 50b8e39e-a895-415d-8c15-7974bdf4ca25
