adx_calendar_initialview: 756150001
adx_calendar_style: 756150000
adx_calendar_timezonemode: 756150000
adx_createRecordDisplayLabel: Create Job Application
adx_createRecordTargetType: 0
adx_createRecordTargetValue: d0c98f8d-6812-4420-b726-75d474a7c08e
adx_deleteRecordDisplayLabel: ''
adx_downloadRecordsDisplayLabel: ''
adx_editRecordDisplayLabel: ''
adx_editRecordTargetType: 0
adx_editRecordTargetValue: ''
adx_emptyListTextMessage: ''
adx_entitylistid: da035abc-9859-4da3-a2f7-b8fb33853fc4
adx_entityname: ss_jobapplications
adx_entitypermissionsenabled: true
adx_filecontent: 
adx_filter_enabled: false
adx_idquerystringparametername: id
adx_isCreateRecord: true
adx_isDeleteRecord: false
adx_isEditRecord: false
adx_isViewRecord: true
adx_lcid: 1033
adx_map_distanceunits: 756150001
adx_map_distancevalues: 5,10,25,50,100
adx_map_infoboxoffsetx: 25
adx_map_infoboxoffsety: 46
adx_map_pushpinheight: 39
adx_map_pushpinwidth: 32
adx_map_resturl: https://dev.virtualearth.net/REST/v1/Locations
adx_map_type: 756150000
adx_map_zoom: 12
adx_mapinfoboxoffsetx: 25
adx_name: Job Application
adx_pagesize: 10
adx_searchenabled: false
adx_settings: >-
  {
    "Type": "CrmEntityFormView-GridMetadata",
    "ViewFormats": [],
    "ViewActions": [
      {
        "Type": "CrmEntityFormView-CreateAction",
        "SuccessMessage": [
          {
            "Type": "LanguageResources",
            "LCID": 1033,
            "Value": "Saved successfully"
          }
        ],
        "TargetType": 0,
        "OnComplete": 0,
        "RedirectWebpageId": "",
        "RedirectUrl": "",
        "EntityFormId": "d0c98f8d-6812-4420-b726-75d474a7c08e",
        "ShowModal": 0,
        "Confirmation": [
          {
            "Type": "LanguageResources",
            "LCID": 1033,
            "Value": ""
          }
        ],
        "ButtonLabel": [
          {
            "Type": "LanguageResources",
            "LCID": 1033,
            "Value": "Create Job Application"
          }
        ],
        "ButtonTooltip": [
          {
            "Type": "LanguageResources",
            "LCID": 1033,
            "Value": ""
          }
        ],
        "ActionIndex": 0,
        "FilterCriteria": ""
      }
    ],
    "ExtendedViewActions": [],
    "ItemActions": [
      {
        "Type": "CrmEntityFormView-DetailsAction",
        "RecordIdQueryStringParameterName": "id",
        "TargetType": 0,
        "OnComplete": 0,
        "RedirectWebpageId": "",
        "RedirectUrl": "",
        "EntityFormId": "3f82e783-941d-469b-8933-a7017ab22640",
        "ShowModal": 0,
        "Confirmation": [
          {
            "Type": "LanguageResources",
            "LCID": 1033,
            "Value": ""
          }
        ],
        "SuccessMessage": [
          {
            "Type": "LanguageResources",
            "LCID": 1033,
            "Value": ""
          }
        ],
        "ButtonLabel": [
          {
            "Type": "LanguageResources",
            "LCID": 1033,
            "Value": "View Job Application"
          }
        ],
        "ButtonTooltip": [
          {
            "Type": "LanguageResources",
            "LCID": 1033,
            "Value": ""
          }
        ],
        "ActionIndex": 0,
        "FilterCriteria": ""
      }
    ],
    "ExtendedItemActions": [],
    "ColumnOverrides": [],
    "LoadingMessage": [
      {
        "Type": "LanguageResources",
        "LCID": 1033,
        "Value": ""
      }
    ],
    "ErrorMessage": [
      {
        "Type": "LanguageResources",
        "LCID": 1033,
        "Value": ""
      }
    ],
    "AccessDeniedMessage": [
      {
        "Type": "LanguageResources",
        "LCID": 1033,
        "Value": ""
      }
    ],
    "EmptyMessage": [
      {
        "Type": "LanguageResources",
        "LCID": 1033,
        "Value": ""
      }
    ],
    "DetailsFormDialog": {
      "Type": "CrmEntityFormView-DetailsFormModal",
      "LoadingMessage": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Size": 1,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "EditFormDialog": {
      "Type": "CrmEntityFormView-EditFormModal",
      "LoadingMessage": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Size": 1,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "CreateRelatedRecordDialog": {
      "Type": "CreateRelatedRecordModal",
      "LoadingMessage": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Size": 1,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "CreateFormDialog": {
      "Type": "CrmEntityFormView-CreateFormModal",
      "LoadingMessage": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Size": 1,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "DeleteDialog": {
      "Type": "CrmEntityFormView-GridDeleteModal",
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Size": 0,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "WorkflowDialog": {
      "Type": "WorkflowModal",
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Size": 0,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "ErrorDialog": {
      "Type": "CrmEntityFormView-ErrorModal",
      "Body": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Size": 0,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "CssClass": "",
    "GridCssClass": "table-striped",
    "GridColumnWidthStyle": 1,
    "ActivateDialog": {
      "Type": "ActivateModal",
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Size": 0,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "DeactivateDialog": {
      "Type": "DeactivateModal",
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Size": 0,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "GetDirectionsDialog": {
      "Type": "GetDirectionsModal",
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Size": 1,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    }
  }
adx_settingsDetails:
  createRecordEntityFormId: []
  createRecordRedirectUrl: &o0 []
  createRecordTargetType: &o1 []
  createRecordWebpageId: *o0
  editRecordEntityFormId: *o0
  editRecordRedirectUrl: *o0
  editRecordTargetType: *o1
  editRecordWebpageId: *o0
  viewRecordEntityFormId: []
  viewRecordRedirectUrl: *o0
  viewRecordTargetType: *o1
  viewRecordWebpageId: *o0
adx_successDeleteRecordMessage: Deleted successfully
adx_successSaveRecordMessage: Saved successfully
adx_view: 6c77d7b4-748b-45a9-89c8-572642486a9b
adx_viewRecordDisplayLabel: View Job Application
adx_viewRecordTargetType: 0
adx_viewRecordTargetValue: 3f82e783-941d-469b-8933-a7017ab22640
adx_views: >-
  {
    "Type": "ViewMetadata",
    "Views": [
      {
        "Type": "View",
        "DisplayName": [
          {
            "Type": "LanguageResources",
            "LCID": 1033,
            "Value": ""
          }
        ],
        "ViewId": "6c77d7b4-748b-45a9-89c8-572642486a9b"
      }
    ]
  }
