adx_accountrelationship: 
adx_append: true
adx_appendto: true
adx_childTablePermissions: []
adx_contactrelationship: ss_jobapplications_Primarycontact_contact
adx_create: true
adx_delete: true
adx_entitylogicalname: ss_jobapplications
adx_entityname: Job Application
adx_entitypermission_webrole:
- 112816ca-53c8-4065-9f1a-b901cfa0f45c
- 3f2062f6-9f46-4b0e-8ad3-5dabbf040644
- fca95bfe-e166-4c92-99cc-4c0ab427d585
adx_entitypermissionid: d9f25466-a95b-4ce9-a176-e22669e08b0c
adx_parententitypermission: 
adx_parentrelationship: 
adx_read: true
adx_scope: 756150001
adx_write: true
