adx_amountColumnName: ''
adx_attachfilelabel: >-
  [
    {
      "LCID": 1033,
      "Value": ""
    }
  ]
adx_attachfilemaxsize: 
adx_attachfilestoragelocation: 756150000
adx_docusignTemplate: ''
adx_entitypermissionsenabled: true
adx_entitysourcetype: 100000001
adx_filecontent: 
adx_formname: Information
adx_geolocation_maptype: 756150000
adx_hideformonsuccess: true
adx_isESignatureEnabled: false
adx_isPaymentEnabled: false
adx_maximumnooffiles: 5
adx_mode: 100000001
adx_movepreviouspermitted: false
adx_name: Edit Job Application
adx_nextstep: 30cccbc9-2f53-4962-be59-5fae903e8d01
adx_primarykeyattributelogicalname: ss_jobapplicationsid
adx_primarykeyquerystringparametername: id
adx_referenceentitysourcetype: 100000001
adx_referencequerystringisprimarykey: true
adx_targetentitylogicalname: ss_jobapplications
adx_type: 100000001
adx_validationsummarylinksenabled: true
adx_webform: 6c049b06-3a8e-4ef3-9a25-2374dde89d39
adx_webFormMetadatas: []
adx_webformstepid: 4f8c5075-7bdf-48ac-8dbe-adecbc65a52c
