- adx_adddescription: false
  adx_attributelogicalname: ss_primarycontact
  adx_descriptionposition: 100000000
  adx_fieldisrequired: false
  adx_ignoredefaultvalue: true
  adx_onsavefromattribute: contactid
  adx_onsavetype: 100000002
  adx_prepopulatefromattribute: fullname
  adx_prepopulatetype: 100000002
  adx_purchasecreateinvoiceonpayment: false
  adx_purchasefulfillorderonpayment: false
  adx_purchaserequiresshipping: false
  adx_randomizeoptionsetvalues: false
  adx_setvalueonsave: true
  adx_type: 100000000
  adx_useattributedescriptionproperty: false
  adx_webformmetadataid: bde228a9-2c50-f011-877a-000d3aca3406
  adx_webformstep: 312faba3-aada-4231-a2b3-ee78cda5e566
